#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App._3dCarousel.Resource", IsApplication=true)]

namespace App._3dCarousel
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int cat = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int fotolia_40649376 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int fotolia_40973414 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int fotolia_48275073 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int fotolia_50806609 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int fotolia_61643329 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int hippo = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int monkey = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int mouse = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int panda = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int rabbit = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int MyButton = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int carousel = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int main_activity = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int activityFragment = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int activityStaticFragment = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] Carousel = new int[] {
					16842927,
					16843026};
			
			// aapt resource value: 1
			public const int Carousel_android_animationDuration = 1;
			
			// aapt resource value: 0
			public const int Carousel_android_gravity = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
